@startuml

Location "1" --> "1" Address
Location "1" --> "*" Product

class Location {
   name : String
   imageurl : String
   address: Address
   type: LocationType
   donationLink: String
}

enum LocationType
{
    BAR
    CAFE
}

class Address {
    city: String
    street: String
    postcode: String
}

class Product {
    name: String
    price: number
    type: ProductType
}

enum ProductType {
    COFFEE
    CAKE
    BEER
    BURGER
}

@enduml
