@startuml

Location "1" --> "1" LocationDetail
Location "1" --> "*" Product

class Location {
    name : String
    imageurl : String
    city: String
    street: String
    postcode: String
    type: LocationType
}

enum LocationType
{
    BAR
    CAFE
}

class LocationDetail {
    ownerName: String
    donationLink: String
    description: String
    lat: number
    lng: number
    googlePlaceId: String
    website: String
}

class Product {
    name: String
    price: number
    type: ProductType
}

enum ProductType {
    COFFEE
    CAKE
    BEER
    BURGER
}

@enduml
